[build]
  publish = "."
  functions = "netlify/functionsnetlify/functions"
 
[[redirects]]
  from = "/imovel/:codigo"
  to = "/imovel.html"
  status = 200
 
[[redirects]]
  from = "/parceiros"
  to = "/parceiros.html"
  status = 200
